from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_CHAT_BOT:
    global select
    def setupUi(self):
        global CHAT_BOT
        CHAT_BOT.setObjectName("CHAT_BOT")
        CHAT_BOT.setWindowModality(QtCore.Qt.WindowModal)
        CHAT_BOT.resize(1285, 1100)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CHAT_BOT.setWindowIcon(icon)
        CHAT_BOT.setAutoFillBackground(False)
        CHAT_BOT.setStyleSheet("background-image: url(:/image/배경.png);")
        self.centralwidget = QtWidgets.QWidget(CHAT_BOT)
        self.centralwidget.setObjectName("centralwidget")
        self.l_love = QtWidgets.QLabel(self.centralwidget)
        self.l_love.setGeometry(QtCore.QRect(30, 963, 151, 31))
        font = QtGui.QFont()
        font.setFamily("08SeoulNamsan")
        font.setPointSize(11)
        self.l_love.setFont(font)
        self.l_love.setStyleSheet("color: rgb(255, 255, 255);")
        self.l_love.setObjectName("l_love")
        self.l_rapunzel = QtWidgets.QLabel(self.centralwidget)
        self.l_rapunzel.setGeometry(QtCore.QRect(280, 963, 111, 31))
        font = QtGui.QFont()
        font.setFamily("08SeoulNamsan")
        font.setPointSize(11)
        self.l_rapunzel.setFont(font)
        self.l_rapunzel.setStyleSheet("color: rgb(255, 255, 255);")
        self.l_rapunzel.setObjectName("l_rapunzel")
        self.l_coco = QtWidgets.QLabel(self.centralwidget)
        self.l_coco.setGeometry(QtCore.QRect(530, 963, 111, 31))
        font = QtGui.QFont()
        font.setFamily("08SeoulNamsan")
        font.setPointSize(11)
        self.l_coco.setFont(font)
        self.l_coco.setStyleSheet("color: rgb(255, 255, 255);")
        self.l_coco.setObjectName("l_coco")
        self.l_sen = QtWidgets.QLabel(self.centralwidget)
        self.l_sen.setGeometry(QtCore.QRect(780, 963, 171, 31))
        font = QtGui.QFont()
        font.setFamily("08SeoulNamsan")
        font.setPointSize(11)
        self.l_sen.setFont(font)
        self.l_sen.setStyleSheet("color: rgb(255, 255, 255);")
        self.l_sen.setObjectName("l_sen")
        self.l_all = QtWidgets.QLabel(self.centralwidget)
        self.l_all.setGeometry(QtCore.QRect(1030, 963, 111, 31))
        font = QtGui.QFont()
        font.setFamily("08SeoulNamsan")
        font.setPointSize(11)
        self.l_all.setFont(font)
        self.l_all.setStyleSheet("color: rgb(255, 255, 255);")
        self.l_all.setObjectName("l_all")
        self.Click_image = QtWidgets.QLabel(self.centralwidget)
        self.Click_image.setGeometry(QtCore.QRect(40, 580, 221, 61))
        font = QtGui.QFont()
        font.setFamily("08SeoulNamsan")
        font.setPointSize(18)
        self.Click_image.setFont(font)
        self.Click_image.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Click_image.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Click_image.setStyleSheet("color: rgb(255, 255, 255);")
        self.Click_image.setObjectName("Click_image")
        self.CHAT_BOT_2 = QtWidgets.QLabel(self.centralwidget)
        self.CHAT_BOT_2.setGeometry(QtCore.QRect(290, 190, 451, 81))
        font = QtGui.QFont()
        font.setFamily("08SeoulNamsan")
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.CHAT_BOT_2.setFont(font)
        self.CHAT_BOT_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CHAT_BOT_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.CHAT_BOT_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.CHAT_BOT_2.setObjectName("CHAT_BOT_2")
        self.WITH_MOVIE = QtWidgets.QLabel(self.centralwidget)
        self.WITH_MOVIE.setGeometry(QtCore.QRect(760, 220, 261, 51))
        font = QtGui.QFont()
        font.setFamily("08SeoulNamsan")
        font.setPointSize(23)
        self.WITH_MOVIE.setFont(font)
        self.WITH_MOVIE.setStyleSheet("color: rgb(255, 255, 255);")
        self.WITH_MOVIE.setObjectName("WITH_MOVIE")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 290, 531, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339795, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339799, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662444, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662469, QtGui.QColor(0, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339795, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339799, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662444, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662469, QtGui.QColor(0, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339795, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339799, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662444, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662469, QtGui.QColor(0, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339795, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339799, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662444, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662469, QtGui.QColor(0, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339795, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339799, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662444, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662469, QtGui.QColor(0, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339795, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339799, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662444, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662469, QtGui.QColor(0, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339795, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339799, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662444, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662469, QtGui.QColor(0, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339795, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339799, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662444, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662469, QtGui.QColor(0, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339795, QtGui.QColor(255, 0, 0))
        gradient.setColorAt(0.339799, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662444, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.662469, QtGui.QColor(0, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("08SeoulNamsan")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.339795 rgba(255, 0, 0, 255), stop:0.339799 rgba(255, 255, 255, 255), stop:0.662444 rgba(255, 255, 255, 255), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 673, 1241, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.p_love = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_love.sizePolicy().hasHeightForWidth())
        self.p_love.setSizePolicy(sizePolicy)
        self.p_love.setMinimumSize(QtCore.QSize(239, 279))
        self.p_love.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.p_love.setStyleSheet("background-image: url(:/image/love.png);")
        self.p_love.setText("")
        self.p_love.setAutoRepeat(True)
        self.p_love.setObjectName("p_love")
        self.p_love.clicked.connect(self.click_1)
        self.horizontalLayout.addWidget(self.p_love)
        self.p_rapunzel = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_rapunzel.sizePolicy().hasHeightForWidth())
        self.p_rapunzel.setSizePolicy(sizePolicy)
        self.p_rapunzel.setMinimumSize(QtCore.QSize(239, 279))
        self.p_rapunzel.setStyleSheet("background-image: url(:/image/rapunzel.png);")
        self.p_rapunzel.setText("")
        self.p_rapunzel.setObjectName("p_rapunzel")
        self.p_rapunzel.clicked.connect(self.click_2)
        self.horizontalLayout.addWidget(self.p_rapunzel)
        self.p_coco = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_coco.sizePolicy().hasHeightForWidth())
        self.p_coco.setSizePolicy(sizePolicy)
        self.p_coco.setMinimumSize(QtCore.QSize(239, 279))
        self.p_coco.setStyleSheet("background-image: url(:/image/coco.png);")
        self.p_coco.setText("")
        self.p_coco.setObjectName("p_coco")
        self.p_coco.clicked.connect(self.click_3)
        self.horizontalLayout.addWidget(self.p_coco)
        self.p_sen = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_sen.sizePolicy().hasHeightForWidth())
        self.p_sen.setSizePolicy(sizePolicy)
        self.p_sen.setMinimumSize(QtCore.QSize(239, 279))
        self.p_sen.setStyleSheet("background-image: url(:/image/sen.jpg);")
        self.p_sen.setText("")
        self.p_sen.setObjectName("p_sen")
        self.p_sen.clicked.connect(self.click_4)
        self.horizontalLayout.addWidget(self.p_sen)
        self.p_all = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_all.sizePolicy().hasHeightForWidth())
        self.p_all.setSizePolicy(sizePolicy)
        self.p_all.setMinimumSize(QtCore.QSize(239, 279))
        self.p_all.setStyleSheet("background-image: url(:/image/all.png);")
        self.p_all.setText("")
        self.p_all.setObjectName("p_all")
        self.p_all.clicked.connect(self.click_5)
        self.horizontalLayout.addWidget(self.p_all)
        CHAT_BOT.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CHAT_BOT)
        self.statusbar.setObjectName("statusbar")
        CHAT_BOT.setStatusBar(self.statusbar)

        self.retranslateUi(CHAT_BOT)
        QtCore.QMetaObject.connectSlotsByName(CHAT_BOT)
        
        
    def click_1(self):
        global select,CHAT_BOT 
        import chat_Love
        CHAT_BOT.close()
        chat_Love.main()
        
##        QtCore.QCoreApplication.instance().quit
    def click_2(self):
        global select,CHAT_BOT 
        import chat_la
        CHAT_BOT.close()
        chat_la.main()
##        QtCore.QCoreApplication.instance().quit
    def click_3(self):
        global select,CHAT_BOT 
        import chat_coco
        CHAT_BOT.close()
        chat_coco.main()

##        QtCore.QCoreApplication.instance().quit
    def click_4(self):
        global select,CHAT_BOT 
        import chat_sen
        CHAT_BOT.close()
        chat_sen.main()

##        QtCore.QCoreApplication.instance().quit
    def click_5(self):
        global select,CHAT_BOT 
        import chat_all
        CHAT_BOT.close()
        chat_all.main()

##        QtCore.QCoreApplication.instance().quit
    def retranslateUi(self, CHAT_BOT):
        _translate = QtCore.QCoreApplication.translate
        CHAT_BOT.setWindowTitle(_translate("CHAT_BOT", "CHAT_BOT"))
        self.l_love.setText(_translate("CHAT_BOT", "Love Actually"))
        self.l_rapunzel.setText(_translate("CHAT_BOT", "Rapunzel"))
        self.l_coco.setText(_translate("CHAT_BOT", "COCO"))
        self.l_sen.setText(_translate("CHAT_BOT", "Sen and Chihiro"))
        self.l_all.setText(_translate("CHAT_BOT", "All Movie"))
        self.Click_image.setText(_translate("CHAT_BOT", "Click image >"))
        self.CHAT_BOT_2.setText(_translate("CHAT_BOT", "CHAT_BOT "))
        self.WITH_MOVIE.setText(_translate("CHAT_BOT", "WITH MOVIE"))
        self.label.setText(_translate("CHAT_BOT", "좋아하는 영화 속 주인공들과 대화해보세요"))
import image
import pdb

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CHAT_BOT = QtWidgets.QMainWindow()
    ui = Ui_CHAT_BOT()
    ui.setupUi()
    CHAT_BOT.show()
    sys.exit(app.exec_())
